//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 11:50:03 PM IDT 
//


package Logic;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="total-players" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="game-title" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DynamicPlayers")
public class DynamicPlayers {

    @XmlAttribute(name = "total-players", required = true)
    protected byte totalPlayers;
    @XmlAttribute(name = "game-title", required = true)
    protected String gameTitle;

    protected List<Player> players;
    private int turnPlayerIndex = 0;
    /**
     * Gets the value of the totalPlayers property.
     * 
     */
    public byte getTotalPlayers() {
        return totalPlayers;
    }

    /**
     * Sets the value of the totalPlayers property.
     * 
     */
    public void setTotalPlayers(byte value) {
        this.totalPlayers = value;
    }

    /**
     * Gets the value of the gameTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGameTitle() {
        return gameTitle;
    }

    /**
     * Sets the value of the gameTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGameTitle(String value) {
        this.gameTitle = value;
    }

    public void addPlayer(Player player)
    {
        if (players == null) {
            players = new ArrayList<>();
        }
        player.init();
        this.players.add(player);
    }

    public List<Player> getPlayers() {
        if (players == null) {
            players = new ArrayList<>();
        }
        return this.players;
    }

    public void init(){
        this.turnPlayerIndex = 0;
        if (players == null) {
            players = new ArrayList<>();
        }
    }

    public Player getActivePlayer(){
        return this.players.get(this.turnPlayerIndex);
    }

    protected void setNextPlayerAsActive(){
        this.turnPlayerIndex = (this.turnPlayerIndex+1+this.players.size())%this.players.size();
    }

    protected void setPreviousPlayerAsActive(){
        this.turnPlayerIndex = (this.turnPlayerIndex-1+this.players.size())%this.players.size();
    }

    protected void remove(Player player){
        if(this.players.contains(player)){
            if(player.equals(getActivePlayer()))
                setPreviousPlayerAsActive();
            if(this.players.indexOf(player)<=this.turnPlayerIndex)
                this.turnPlayerIndex--;

            this.players.remove(player);
        }
    }

}
